# Generated by Django 4.2 on 2023-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='Order Title', max_length=255),
        ),
    ]
